### PR TITLE
glob function used instead of dirent.h

### PR DESCRIPTION
**Pull request by sturkmen72**

### CODE REVIEW

**Comment by BlcaKHat** [comment]
I couldn't did it yet. hemp me.

**Comment by BlcaKHat** [comment]
can you implement it in python

**Comment by sturkmen72** [comment]
see https://github.com/opencv/opencv/blob/master/samples/python/squares.py#L46-L48

**Comment by BlcaKHat** [comment]
it's odd to ask. but I am not able to implement it in this code.
it would be a great help if you help me.

**Comment by BlcaKHat** [comment]
thanx @sturkmen72  
It would be great if you help me with detecting just one class. thank you...

**Comment by spmallick** [comment]
Ok, I need to make it a priority to test it on windows and linux. My apologies.

**Pull request closed without merging**
