### PR TITLE
Efficient image loading

### PR DESCRIPTION
**Pull request by MaximKuklin**

### CODE REVIEW

**Comment by MaximKuklin** [comment]
@tkhanova @vkoriukina

**Comment by vikasguptaiisc** [comment]
This is good to go!

**Comment by brmarkus** [comment]
The blog "https://www.learnopencv.com/efficient-image-loading/" mentions a "requirement.txt" to "install the required libraries".
Where can this file be found in the context of "efficient image loading"?

**Comment by MaximKuklin** [comment]
@brmarkus, sorry for that, I've added new requirements.txt file with the[ latest commit ](https://github.com/spmallick/learnopencv/pull/426/commits/34980652b4644ea497a2191e1b9046ad2602185d)

**Pull request merged**
