### PR TITLE
Added Rock, Paper, Scissor Code.

### PR DESCRIPTION
**Pull request by TahaAnwar**

### CODE REVIEW

**Comment by brmarkus** [comment]
Can you document the dependencies/requirements, please? What in which version would be required to be installed (like a `requirements.txt`, used via `pip install`)?

**Comment by brmarkus** [comment]
Will you provide a blog as well?

**Comment by brmarkus** [comment]
The reason why I ask for the dependencies is that I cannot load the model, but get an exception `ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))`, which might be raised due to incompatible API-changes from TF1.14 to TF1.15, so you might recommend to use specific versions, maybe recommend to use a virtual-environment.

**Comment by TahaAnwar** [comment]
> Can you document the dependencies/requirements, please? What in which version would be required to be installed (like a `requirements.txt`, used via `pip install`)?

Hi, that's not necessary, the code will work with any OpenCV 3 + version and Tensorflow 2.0 although I think older versions would also work, all the details are explained in the Blog post, which is ready to be published. Satya just needs to upload some videos to youtube and provide me with the link so I can put them inside the post. Then you hit publish.

**Comment by TahaAnwar** [comment]
> The reason why I ask for the dependencies is that I cannot load the model, but get an exception `ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))`, which might be raised due to incompatible API-changes from TF1.14 to TF1.15, so you might recommend to use specific versions, maybe recommend to use a virtual-environment.

Didn't knew that, since I used TF 2.0 so maybe the model can be only be loaded using TF 2.0 + versions only. Also the model is optional and its recommended that everyone trains their own model for their own backgrounds.

I would add the instruction for the user to use TF 2.0 in the blog post.

**Comment by TahaAnwar** [comment]
> Will you provide a blog as well?

Yes

**Comment by csjhhuc** [comment]
unsubscribe



At 2020-07-13 18:06:05, "TahaAnwar" <notifications@github.com> wrote:

Can you document the dependencies/requirements, please? What in which version would be required to be installed (like a requirements.txt, used via pip install)?

Hi, that's not necessary, the code will work with any OpenCV 3 + version and Tensorflow 2.0 although I think older versions would also work, all the details are explained in the Blog post, which is ready to be published. Satya just needs to upload some videos to youtube and provide me with the link so I can put them inside the post. Then you hit publish.

**Comment by TahaAnwar** [comment]
> unsubscribe At 2020-07-13 18:06:05, "TahaAnwar" <notifications@github.com> wrote: Can you document the dependencies/requirements, please? What in which version would be required to be installed (like a requirements.txt, used via pip install)? Hi, that's not necessary, the code will work with any OpenCV 3 + version and Tensorflow 2.0 although I think older versions would also work, all the details are explained in the Blog post, which is ready to be published. Satya just needs to upload some videos to youtube and provide me with the link so I can put them inside the post. Then you hit publish. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi It's added

**Comment by brmarkus** [comment]
> > Will you provide a blog as well?
> 
> Yes

Can you add the URL pointing to the blog to the `README.md`, please?

**Comment by brmarkus** [comment]
> > unsubscribe At 2020-07-13 18:06:05, "TahaAnwar" [notifications@github.com](mailto:notifications@github.com) wrote: Can you document the dependencies/requirements, please? What in which version would be required to be installed (like a requirements.txt, used via pip install)? Hi, that's not necessary, the code will work with any OpenCV 3 + version and Tensorflow 2.0 although I think older versions would also work, all the details are explained in the Blog post, which is ready to be published. Satya just needs to upload some videos to youtube and provide me with the link so I can put them inside the post. Then you hit publish. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Hi It's added

I can confirm it's working for me now, thank you.

**Comment by TahaAnwar** [comment]
> > > Will you provide a blog as well?
> > 
> > 
> > Yes
> 
> Can you add the URL pointing to the blog to the `README.md`, please?

done

**Comment by TahaAnwar** [comment]
Its added

**Comment by csjhhuc** [comment]
unsubscribe



At 2020-07-13 20:00:00, "TahaAnwar" <notifications@github.com> wrote:

Its added

**Comment by TahaAnwar** [comment]
Hi, can you merge this pull request?

**Pull request merged**
