### PR TITLE
Added files and projects

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**

### CODE REVIEW

**Comment by ShubhamJagtap2000** [comment]
Added code files and video files for YOLOv3-Object-Detection

**Comment by ShubhamJagtap2000** [comment]
Sir/Ma'am, will ypu mind merging my pull requests? You can suggest me to explain or improvements, much appreciated.

**Comment by brmarkus** [comment]
Can you provide an overview and description what the "Motion and object tracker for a video" is about, please? Are you intending to add topics like "PageScanner.py" and "Barcode detection from an image" under "motion and object tracker for a video"...?

**Comment by ShubhamJagtap2000** [comment]
> Can you provide an overview and description what the "Motion and object tracker for a video" is about, please? Are you intending to add topics like "PageScanner.py" and "Barcode detection from an image" under "motion and object tracker for a video"...?

"Motion and Object tracker will track the moving objects like, persons in the video file test.avi that is provided. It can be applied to other videos with moving objects as well. 

No I would like to make separate repos for Page Scanner Application and Barcode Detector as they are a different projects/applications of the OpenCV.

If you want any improvements in the pull requests. please suggest.

**Comment by brmarkus** [comment]
Then I would suggest you remove all those other files/commits not related to "Motion and object tracker for a video".
If this your PullRequest would be accepted and merged then all those other resources for the other topics (barcode, page-scanner, etc.) would be taken-over.

**Comment by ShubhamJagtap2000** [comment]
Okay. I will make a different PR for them.

**Comment by ShubhamJagtap2000** [comment]
> Then I would suggest you remove all those other files/commits not related to "Motion and object tracker for a video". If this your PullRequest would be accepted and merged then all those other resources for the other topics (barcode, page-scanner, etc.) would be taken-over.

Actually, I have made separate folders for each of the projects, even if you merge, everything will be added separately. Thay will not lead to any mixup.

**Comment by ShubhamJagtap2000** [comment]
Ohh... that will take time. Okay, I will do separately...

**Comment by ShubhamJagtap2000** [comment]
I will close this PR and do it separately. Thank you sir.

**Pull request closed without merging**
